#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx test',
    source=bld.path.ant_glob('**/*.cpp'),
    target='kodo_fulcrum_tests',
    use=['kodo_fulcrum_includes', 'kodo_core_unit_test_includes', 'gtest',
         'stub_includes', 'boost_filesystem', 'boost_system',
         'boost_program_options'])
